### ISSUE TITLE
[DS105] Create and setup initial Moodle page skeleton

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/lse-ds105-course-notes#64]

**Comment by OCQUAYE1** [comment]
Hello Jon,

please is this 'initial Moodle page skeleton' for the slack channels? if yes, then I have labelled each week with the topic. however, the main LSE Moodle page is something I am/will work on with Dave shortly, should be ready latest by Monday.

**Comment by jonjoncardoso** [comment]
Thanks Nathaniel. This actually refers to the Moodle pages indeed (details on the e-mail).
