### ISSUE TITLE
[DS105] Create a list of suggested APIs

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/lse-ds105-course-notes#66]
Stuart

**Comment by mc-o** [comment]
Added a list as a qmd file . 80aca8f1bb844ddcdedb9f1cb611cf25c4c677ac  can be updated as new APIs are added.

**Comment by mc-o** [comment]
[api_list.html](https://github.com/LSE-DSI/lse-ds105-course-notes/blob/66-mc-o-ds105-create-a-list-of-suggested-apis/resources/week04/api_list.html) and [api_list_files/libs](https://github.com/LSE-DSI/lse-ds105-course-notes/tree/80aca8f1bb844ddcdedb9f1cb611cf25c4c677ac/resources/week04/api_list_files/libs) can be removed

**Comment by jonjoncardoso** [comment]
Deployed to main webpage
